let map = new Map()
map.set("chips", 12)
map.set("cold drink", 10)
map.set("tandori", 4)
console.log(map)
console.log(map.size)
console.log(map.has("chips"))
console.log(map.get("cold drink"))
console.log(map.set("water", 14))
map.clear()
console.log(map)
